apiVersion: v1
kind: Service
metadata:
  name: api-gateway
  namespace: ticketing
spec:
  type: NodePort
  selector:
    app: api-gateway
  ports:
    - port: 8080          
      targetPort: 8080    
      nodePort: 30080     
      protocol: TCP
