apiVersion: batch/v1
kind: Job
metadata:
  name: cockroachdb-init
  namespace: ticketing
spec:
  backoffLimit: 3
  template:
    spec:
      restartPolicy: OnFailure
      containers:
        - name: cockroachdb-init
          image: cockroachdb/cockroach:v23.2.0
          command:
            - sh
            - -c
            - |
              echo "Waiting for CockroachDB SQL to be ready..."

              # Wait until SQL responds
              until cockroach sql --insecure --host=cockroachdb-client -e "SELECT 1;" >/dev/null 2>&1; do
                echo "CockroachDB not ready..."
                sleep 2
              done

              echo "CockroachDB is ready."
              echo "Creating database ticketdb..."

              cockroach sql --insecure --host=cockroachdb-client -e "
                CREATE DATABASE IF NOT EXISTS ticketdb;
              "

              echo "Initialization complete."


