apiVersion: v1
kind: Service
metadata:
  name: cockroachdb
  namespace: ticketing
spec:
  clusterIP: None
  selector:
    app: cockroachdb
  ports:
    - name: sql
      port: 26257
      targetPort: 26257
    - name: http
      port: 8080
      targetPort: 8080
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: cockroachdb
  namespace: ticketing
spec:
  serviceName: cockroachdb
  replicas: 3
  selector:
    matchLabels:
      app: cockroachdb
  template:
    metadata:
      labels:
        app: cockroachdb
    spec:
      hostname: cockroachdb
      subdomain: cockroachdb
      containers:
        - name: cockroachdb
          image: cockroachdb/cockroach:v23.2.0
          args:
            - "start"
            - "--insecure"
            - "--advertise-addr=$(HOSTNAME).cockroachdb.ticketing.svc.cluster.local"
            - "--join=cockroachdb-0.cockroachdb.ticketing.svc.cluster.local,cockroachdb-1.cockroachdb.ticketing.svc.cluster.local,cockroachdb-2.cockroachdb.ticketing.svc.cluster.local"
          ports:
            - name: sql
              containerPort: 26257
            - name: http
              containerPort: 8080
          volumeMounts:
            - name: cockroachdb-data
              mountPath: /cockroach/cockroach-data
  volumeClaimTemplates:
    - metadata:
        name: cockroachdb-data
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 5Gi
---
apiVersion: v1
kind: Service
metadata:
  name: cockroachdb-client
  namespace: ticketing
spec:
  type: ClusterIP
  selector:
    app: cockroachdb
  ports:
    - name: sql
      port: 26257
      targetPort: 26257
