apiVersion: batch/v1
kind: Job
metadata:
  name: cockroachdb-init
  namespace: ticketing
spec:
  backoffLimit: 3
  template:
    spec:
      restartPolicy: OnFailure
      containers:
        - name: cockroachdb-init
          image: cockroachdb/cockroach:v23.2.0
          command:
            - sh
            - -c
            - |
              echo "Waiting for node 0 SQL..."

              until cockroach sql --insecure \
                --host=cockroachdb-0.cockroachdb.ticketing.svc.cluster.local \
                -e "SELECT 1;" >/dev/null 2>&1; do
                echo "Node 0 not ready..."
                sleep 2
              done

              echo "Creating database ticketdb..."
              cockroach sql --insecure \
                --host=cockroachdb-0.cockroachdb.ticketing.svc.cluster.local \
                -e "CREATE DATABASE IF NOT EXISTS ticketdb;"

              echo "Init complete!"

