apiVersion: batch/v1
kind: Job
metadata:
  name: cockroachdb-init
  namespace: ticketing
spec:
  backoffLimit: 0
  template:
    spec:
      restartPolicy: Never
      containers:
      - name: cockroachdb-init
        image: cockroachdb/cockroach:v23.2.0
        command:
        - sh
        - -c
        - |
          echo "Waiting for CockroachDB SQL to be fully ready..."

          # Wait until node responds
          while true; do
            if cockroach sql --insecure --host=cockroachdb-client -e "SELECT 1;" >/dev/null 2>&1; then
              echo "CockroachDB is ready!"
              break
            fi
            echo "CockroachDB not ready..."
            sleep 2
          done

          echo "Creating database ticketdb..."

          # Retry CREATE DATABASE forever
          while true; do
            cockroach sql --insecure --host=cockroachdb-client \
              -e "CREATE DATABASE IF NOT EXISTS ticketdb;" >/dev/null 2>&1

            if [ $? -eq 0 ]; then
              echo "Database ticketdb created!"
              break
            fi

            echo "Failed to create DB, retrying..."
            sleep 2
          done

          echo "Initialization complete!"




