apiVersion: batch/v1
kind: Job
metadata:
  name: cockroachdb-init
  namespace: ticketing
spec:
  backoffLimit: 10
  template:
    spec:
      restartPolicy: OnFailure
      containers:
        - name: cockroachdb-init
          image: cockroachdb/cockroach:v23.2.0
          command:
            - sh
            - -c
            - |
              echo "Waiting for CockroachDB SQL port..."
              until nc -z cockroachdb-client 26257; do
                echo "CockroachDB not ready, retrying..."
                sleep 3
              done

              echo "CockroachDB is ready! Initializing..."

              cockroach sql --insecure --host=cockroachdb-client -e "
                CREATE DATABASE IF NOT EXISTS ticketdb;
              "

              cockroach sql --insecure --host=cockroachdb-client -e "
                CREATE USER IF NOT EXISTS ticketuser WITH PASSWORD 'mypassword';
              "

              cockroach sql --insecure --host=cockroachdb-client -e "
                GRANT ALL ON DATABASE ticketdb TO ticketuser;
              "

              echo "Initialization complete."
