apiVersion: batch/v1
kind: Job
metadata:
  name: cockroachdb-init
  namespace: ticketing
spec:
  backoffLimit: 5
  template:
    spec:
      restartPolicy: OnFailure
      containers:
        - name: init
          image: cockroachdb/cockroach:v23.2.0
          command:
            - sh
            - -c
            - |
              echo "Waiting for CockroachDB SQL..."

              until cockroach sql --insecure --host=cockroachdb-client -e "SELECT 1;" >/dev/null 2>&1; do
                echo "CockroachDB not ready, waiting..."
                sleep 3
              done

              echo "Initializing database..."

              cockroach sql --insecure --host=cockroachdb-client -e "
                CREATE DATABASE IF NOT EXISTS ticketdb;
                CREATE USER IF NOT EXISTS ticketuser WITH PASSWORD 'mypassword';
                GRANT ALL ON DATABASE ticketdb TO ticketuser;
              "

              echo "Initialization complete."
